### ISSUE TITLE
AttributeError in OpenFile.__del__()

### ISSUE THREAD

**Issue by morbult** [domna/tdm_loader#11]
Multiple times I have got this error and I don't know why. I guess it happens when OpenFile objects are being destroyed in the background and `OpenFile.__del__()` is being called.
Error message:
```
Traceback (most recent call last):
  File "c:\tdm_loader\tdm_loader.py", line 520, in __del__
    self.close()
  File "c:\tdm_loader\tdm_loader.py", line 494, in close
    self._tdx_fobj.close()
AttributeError: 'OpenFile' object has no attribute '_tdx_fobj'
```
I don't know how to reproduce the error, but it should be solved by replacing the code in OpenFile.close()
```python
self._tdx_fobj.close()
```
with
```python
if hasattr(self, '_tdx_fobj'):
    self._tdx_fobj.close()
```

**Comment by domna** [comment]
Done and fixed in version 1.1.9
