### ISSUE TITLE
ParseError if tdx file is not well-formed

### ISSUE THREAD

**Issue by Aquapisces** [domna/tdm_loader#13]
The tdm files I'm dealing with are not all well-formed, numbers of the channels maybe different sometimes.
Therefore, I should replace the blank with NaN. However, when I open these tdm/tdx file with tdm_loader.OpenFile() in iPython, I got an ParserError:
`ParseError: not well-formed (invalid token): line 1, column 1`
Would you please make these baddish tdm/tdx files readable with tdm loader?
Thanks a lot^_^

**Comment by domna** [comment]
Could you post the full error-trace and the files producing this error, please?

**Comment by Aquapisces** [comment]
I think it's not difficult to solve this problem by myself, and I have made it. Thank you all the same!
