### ISSUE TITLE
issue with get_column_index

### ISSUE THREAD

**Issue by ras-sim** [domna/tdm_loader#15]
Hi,

there is an issue with the "get_column_index" function, when using a str instead of an int. 
I guess the if statement at the beginning (if channel_group < 0 or channel < 0:) is the root cause for the issue.

Best regards

Florian

**Comment by domna** [comment]
Hi,

yes, there is an instance check missing in this function. I will correct this later today and upstream the new version.

Thank you.

**Comment by domna** [comment]
Fixed in 1.1.15 (as now available over pypi).
