### ISSUE TITLE
Problem loading files after numpy update

### ISSUE THREAD

**Issue by morbult** [domna/tdm_loader#16]
I recently started getting the following error in `MemmapColumnFirst.__init__` when loading files:
```py3
    self._empty_row[0] = pack('') # initialize all items to zero

ValueError: could not convert string to float: 
```
The only reason I can find is that numpy was updated from version 1.13.1 to 1.14.2. Loading works if I change the line to `self._empty_row[0] = 0`, although I have no idea why, but then it instead fails with a `TypeError: a bytes-like object is required, not 'int'` on the same line if I go back using numpy 1.13.1 again.
I tested the sample file test_sample0001.tdm so you should be able to reproduce the error.

**Comment by domna** [comment]
This error is fixed in the current tdm_loader version (which also requires numpy >= 1.14).

**Comment by morbult** [comment]
Oh, I did't notice it was already changed... Great!
