### ISSUE TITLE
xml.etree.ElementTree ParseError: not well-formed

### ISSUE THREAD

**Issue by cclabelle** [domna/tdm_loader#20]
I have TDM/TDX files I'm trying to read using the following syntax:

import tdm_loader
data_file = tdm_loader.OpenFile('filename.tdm')

And I receive this error:
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2

I hope there's an easy solution at my end... I uploaded some sample files.

[TDM-TDX_Files.zip](https://github.com/domna/tdm_loader/files/4421463/TDM-TDX_Files.zip)

**Comment by domna** [comment]
It is because your tdm file is not in XML format. With which program did you save those files?
With tdm_loader it is only possible to read tdm/tdx as xml/binary representation (which, however, should be the right format, according to ni defintions).

**Comment by cclabelle** [comment]
Hello Mr. Dobener,
Thanks for your response.This data has been saved out from DIADEM.This is test data from a dynamometer.I don't have DIADEM so normally I open the data in Excel using a "TDM Importer" add-in.This normally works fine, but in some cases the data is so huge that Excel is overwhelmed.I think Python would be more efficient way to access the data.
Is your conclusion then that I will not be able to access this data in Python?
Best Regards,Chad    On Friday, April 3, 2020, 02:41:36 p.m. EDT, Florian Dobener <notifications@github.com> wrote:  
 
 


It is because your tdm file is not in XML format. With which program did you save those files?
With tdm_loader it is only possible to read tdm/tdx as xml/binary representation (which, however, should be the right format, according to ni defintions).

**Comment by domna** [comment]
In the current state of tdm_loader it is not possible with it to read the files you supplied. However, I do not know if this is just some form of compressed xml representation or if it is maybe possible to save the data in a compatible tdm form from DIADEM.

I will try to figure out what the data type definition your files are and will see if it is possible to get the data to work with tdm_loader.

**Comment by domna** [comment]
Thanks to the work of @femoor these files are working now (see issues #22 #23 ) in version 1.2.2
