### ISSUE TITLE
data_file.channel_dict(). IndexError: list index out of range

### ISSUE THREAD

**Issue by liuminxing** [domna/tdm_loader#21]
./tdm_loader.py in channel(self, channel_group, channel, occurrence, ch_occurrence)
    229         lc = self._root.find(".//localcolumn[@id='{0}']".format(lc_usi))
    230         repr = lc.findtext('sequence_representation')
--> 231         data_usi = OpenFile._get_usi_from_txt(lc.findtext('values'))[0]
    232         inc = self._root.find(".//{0}[@id='{1}']/values".format(datatype, data_usi))

data_file=tdm_loader.OpenFile('.\data_to_read.TDM','.\data_to_read.tdx')
I can get the information about the file as following:
Number of Channelgroups: 6
Channel Length: 6
but i can't use channel_dict to get the dictionary
if i run **data_file.channel_dict(1)**, i get the error which i display at the beginning.

I can't find the reason.
Besides, i can use the same script to read other files......
I check the file with Diadem but i don't notice any errors.

Can anyone help me?

**Comment by domna** [comment]
Can you please post the actual error message? It should be below the error trace you posted already.
To help you best it would be helpful for me, if you could provide the file, which causes the error.

**Comment by liuminxing** [comment]
> 
> 
> Can you please post the actual error message? It should be below the error trace you posted already.
> To help you best it would be helpful for me, if you could provide the file, which causes the error.

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-33d9ee93e364> in <module>
      2 data_file.channel_name(4,55)
      3 data_file.channel(4,55)
----> 4 data_file.channel_dict(4)

~\.conda\envs\tf_cpu\lib\site-packages\tdm_loader\tdm_loader.py in channel_dict(self, channel_group, occurrence)
    266             for i in range(self.no_channels(channel_group)):
    267                 name = self.channel_name(channel_group, i)
--> 268                 ch = self.channel(channel_group, i)
    269                 if name in channel_dict:
    270                     name_doublets.add(name)

~\.conda\envs\tf_cpu\lib\site-packages\tdm_loader\tdm_loader.py in channel(self, channel_group, channel, occurrence, ch_occurrence)
    229         lc = self._root.find(".//localcolumn[@id='{0}']".format(lc_usi))
    230         repr = lc.findtext('sequence_representation')
--> 231         data_usi = OpenFile._get_usi_from_txt(lc.findtext('values'))[0]
    232         inc = self._root.find(".//{0}[@id='{1}']/values".format(datatype, data_usi))
    233 

IndexError: list index out of range


i just run these codes below: and it occurs the error which described as above.

data_file = tdm_loader.OpenFile('C:\test\measurement_1.TDM','C:\test\measurement_1.tdx')
data_file.channel_dict(4)

the data_file has the property:
Number of Channelgroups: 6
Channel Length: 6

**Comment by liuminxing** [comment]
Thanks for your reply. I’m very appreciative of your help. I wrote you back
on GitHub.
It will be better, if you don’t need to look into the data File. But if is
too difficult to locate the reason without the data file, please let me
know.

It is very strange that i can get the structure of the data, I can also get
the value as rec.array using channel(4,55). But I can’t use channel_dict(4)
to get the dictionary.

best wishes
Minxing

**Comment by domna** [comment]
To track the error I would need to have a look at a sample file with which I can reproduce the error. There is some difference in the internal structure of the tdm file you have.
Could you provide me the file?

**Comment by liuminxing** [comment]
Thanks a lot. I find an error in my data file. I solved the problem by
deleting the certain channel. It works again.

**Comment by domna** [comment]
Great that it works now. If you have any further questions don't hestiate to ask.
