### ISSUE TITLE
sequence_representation support

### ISSUE THREAD

**Issue by femoor** [domna/tdm_loader#23]
currently, only accessing channels of `explicit` _sequence_representation_ is supported.
that means data stored as float numbers, directly.

If you try to access a time channel, this may fail since time channels typically are even-spaced and therefore can be constructed by very few parameters.
In that case,  `sequence represetation` is `implicit_linear`.

After some issues with unprocessed measurement data (` AttributeError: 'NoneType' object has no attribute 'get'`), I examined the xml structure of the TDM file and also discovered a third sequence represetation type: `raw_linear`.
That means mapping measurement data on an integer range via two generation parameters (both float).
I think this is reasonnable for typically coarse and even-spaced measurement device resolution.

So I expanded the `channel` method by a sequence represetation check and handling.

I would like to share this, as #22, as well.

**Comment by domna** [comment]
Hi femoor,

thank you for participating. Would you share your changes as a PR? I would then review it and issue a new release with the changes.

**Comment by femoor** [comment]
Hello domna

Yes I would like to!
We currently have a big measurement project across several companies running. 
We are using my described fixes, but for distributing these, I think it is much prettier to update Your package globally than spreading some single command lines.

PR means pull request, right..? -- I'm sorry, I'm totally new here. 
I just installed git the first time and yet haven't any experience.
If i got it right, i'll now have to somehow integrate that into vscode in my case.
I think i'll get through that but please excuse if it may take few days -- im still practicing.

Alternatively i could of course send you the new lines directly via email or so and tell where to put.
Might be faster.
But if it's okay for you I would prefer the git way.

**Comment by domna** [comment]
That's fine, I can guide you through the process of pull requesting (which is abbreviated PR, yes). 
You can use git on the command line directly or from vs code directly. You'll find plenty of tutorials when you google it.

Typically to create a PR you fork the repository into your own github account (just click fork top right here on github). Then you clone your forked repository and commit your changes via git. Then you can create a PR from your fork to my main repository over the github web frontend. If you're stuck somewhere, feel free to ask for help!

**Comment by femoor** [comment]
Fine!
Thanks for your hints. 
That's roughly what i learnt yesterday watching youtube, but it's helpful for me reading the same from a second person.

I'll try through it and maybe i'll have to come back to you. 
So thank you in advance!

**Comment by femoor** [comment]
I did so and just created a PR.
Now i hope i did it all correctly.

One question: 
The pull request is now "open".
Do i have to keep it open or do i have to close it now for you to access it?

**Comment by domna** [comment]
Great! Congrats on your first PR. Looks good to me and you can just leave the PR open. I'll close it when I merge it into the main branch.

**Comment by domna** [comment]
Do you have any zip files you could provide? Ideally for each change you made. Then I would be able to create tests for your changes (or if you want you could create the tests yourself).
Anyways, I think I'll take some time with the PR as I want to set up a continuous integration pipeline and polish the package structure and tests, just to be sure the changes don't break any old code.

**Comment by femoor** [comment]
zip files - What do you mean with that?

**Comment by domna** [comment]
I meant tdm files with zip compression.

**Comment by femoor** [comment]
Ah okay.

Yes, of course i can provide some zipped tdm files -- we have enough of them!
but my corresponding tdx s are typically about 5GB big at the moment, so i think i'll better look for smaller ones.
And ideally some more, each providing one of my issues seperately -- i think now i got you.
That is a good idea.

(vice versa i should have checked if the handling works fine on _non_-zip tdm, as well. I'm not really sure if i did that)

But that may take some time and i'm busy at the moment.
would it be okay for you to wait until friday afternoon?

**Comment by domna** [comment]
Perfect. Maybe you can just cut most of the data, such that you have a little representative tdx file.
I already have tests for non-zip tdm's, so don't worry about this case. I'll do the tests (but that's why I wanted to update the project structure ;)

Don't worry about the time. You're contributing your own time here and there's no point in rushing it. I think I will need some time myself to finish everything for a new release.

**Comment by domna** [comment]
Allright, I finished my changes and I am ready to publishing a new release. However, I think it would be useful to test the import for zip-based tdm's first. I made some changes in your import of zip based tdm files (basically using with for opening files and raising an error, when the zip file does not contain any files). So maybe you can test it against your data? Ideally we would have automated tests for zip-based tdm's before publishing.

**Comment by femoor** [comment]
Okay.
Now i have a small tdm/tdx file for you. It's a zip-compressed one and contains channels with all of the three different described sequence representatiopn types.

So tdm_loader 1.2.1 will fail on that tdm.
You can extract the xml file as described and then read the explicit channels with tdm_loader 1.2.1
But when trying to read a linear_implicit channel (time) this won't work properly, as already mentioned somewhere in the code. 
when trying to read a raw_linear channels, it will return an error.

I also quickly wrote a short test py script for that tdm, that checks for all of my issues.

How am I to send it to you? 
Is this possible somewhere here on github?

**Comment by domna** [comment]
Perfect. You can simply drag&drop the file into the text field and it'll be uploaded.
You can alternatively put it into https://github.com/domna/tdm_loader/tree/master/tdm_loader/tests/test_non_zip_tdm directory, ideally together with your test into https://github.com/domna/tdm_loader/tree/master/tdm_loader/tests and once again issue an PR with it.

**Comment by femoor** [comment]
"Uploads are disabled.
File uploads require push access to this repository."

What do i have to do now?

**Comment by domna** [comment]
mmh... I don't know. I thought that upload in the comments should work regardless of repo access rights. Anyways you can use gists: https://gist.github.com

**Comment by femoor** [comment]
it says upload fails on file ending.
Ill try to put all into one zip file. 
zip is accepted. :)

your invitation won't work also. it says
"Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account."

**Comment by femoor** [comment]
...and drag&dropping a zip archive with the files also fails.

**Comment by femoor** [comment]
i looks as gist is only for text code.

But the py file only won't help you.

**Comment by femoor** [comment]
You now must have recieved three files.

I hope, but I'm not sure if that worked because 

"Outlook hat den Zugriff  auf die folgenden potenziell unsicheren [...] : testtdmloader121.py"

**Comment by domna** [comment]
The changes are released in version 1.2.2. Don't worry about the failing tests in gh, they are just due to the worker. Locally all tests work and I'll figure out what's wrong in the next days.

Thank you for your contribution!
