### ISSUE TITLE
Add function for conversion to dict, OpenFile.to_dict()

### ISSUE THREAD

**Issue by morbult** [domna/tdm_loader#6]
I've been having problems understanding channel indices and column inideces and how to correctly loop through all the channels in a file. What I want to do is to get all the channels in a dict with channel names as keys. The code I'm using now which seems to work fine 
```python
df = tdm_loader.OpenFile(tdm_file_name)
tdm_dict = {}
for i_grp in range(df.no_channel_groups()):
    for i_ch in range(df.no_channels(i_grp)):
        name = df.channel_name(i_grp, i_ch)
        ch = df.channel(i_grp, i_ch)
        tdm_dict[name] = np.array(ch)
```
At first I tried to loop through `df.channel_names` and use the corresponding index to get the channel with `df[i]`, but that apparently jumble the names vs channels.

It would be nice to have a convenient function for converting to dict of ndarray, e.g. `OpenFile.to_dict()`. I don't know though how this would work if there are more than one channel group in a file, all my files only have one.

Alternatively give example in README on how to do something like this, or just how to loop through and get correct pairing (channel name, channel data).

**Comment by domna** [comment]
The channel indices are the correct representation as files are saved (in channel group and channel references). The column indices are a bit complicated and depend on the internal structure of the tdm/tdx files, they represent the order in which the data is written in the binary file. The best way is to rely on channel indices, since in future releases I like to cut down the use of the column notation.

An option for your problem could be to generate a dictionary for a specific group, e.g. `OpenFile.to_dict("channel group_name")`, would this be sufficient for you?

**Comment by domna** [comment]
I updated the code with an additional function OpenFile.channel_dict("channel group name") with gives you a dict of the given channel group.

**Comment by morbult** [comment]
Nice! Exactly what I need.

I do think it's a good idea to cut down the use of column notation. In fact I was thinking it might be good to change the behaviour of `data_file[column_num]` and instead use these options
```python
data_file[channel_group, channel]  # int, int
data_file[channel]  # int (with channel_group 0)
data_file[channel_name]  # string
```
I think it's more useful and inuitive than the column notation. Here is an implementation for that syntax.
```python
def __getitem__(self, key):
    if isinstance(key, tuple):
        if len(key) != 2:
            raise IndexError(key)
        channel_group, channel = key
        if isinstance(channel, int):
            return self.channel(channel_group, channel)
        else:
            raise TypeError(channel)
    elif isinstance(key, str):
        if key in self.channel_names:
            _, channel_group, channel = self.channel_search(key)[0]
            return self.channel(channel_group, channel)
        else:
            raise KeyError(key)
    else:
        return self[0, key]  # Use channel_group 0
```

**Comment by domna** [comment]
Yes that is a nice suggestion. I added your code into the dev branch and added some additional features to access the channels by name in the appropriate functions.
I will write tests for the new features the next days and then I'll bring the changes in the main branch & update the pypi package.
