### ISSUE TITLE
Problem with number of "block" tags

### ISSUE THREAD

**Issue by morbult** [domna/tdm_loader#9]
In several tdm files I've tested, there are more "block" tags than "tdm_channel" tags, which made `assert(len(blocks) == len(channel_names))` to fail. This might be i dirty fix to that problem `assert(len(blocks) >= len(channel_names))`, but I don't have a better idea right now.

What I noted with those tdm file was that the few extra "block" tags are always the last ones, they always have valueType="eInt16Usi", and their id is always linked to a "flags" tag instead of a "double_sequence" or "long_sequence" tag.

**Comment by domna** [comment]
Yes I also had that problem some times. I'm not quite sure yet why sometimes these block tags are created, but I think the best way to go right now would be to drop this assertion. I also did this manually when this error occurred.
